# This workflow can be triggered by another repository to build Docker images using docker bake

name: Docker Bake
run-name: "Docker Bake | Actor: ${{ github.actor }} | Repo: ${{ github.event.client_payload.source_rep }} | Ref: ${{ github.event.client_payload.source_ref }} | Variant: ${{ github.event.client_payload.dockerfile_variant || 'standard' }}"

# This workflow is designed to be triggered by repository_dispatch events
on:
  repository_dispatch:
    types: [event-bake]

concurrency:
  group: ${{ github.event.client_payload.source_rep }}-${{ github.event.client_payload.source_ref }}
  cancel-in-progress: true

env:
    SOURCE_REP: ${{ github.event.client_payload.source_rep }}
    SOURCE_REF: ${{ github.event.client_payload.source_ref }}
    RUNNER_TYPE: ${{ github.event.client_payload.runner || 'ubuntu-latest' }}

jobs:
    docker-bake:
        name: "Build Docker Image for ${{ github.event.client_payload.source_rep }}@${{ github.event.client_payload.source_ref }}"
        runs-on: ${{ github.event.client_payload.runner || 'ubuntu-latest' }}
        steps:
        - name: Display trigger information
          run: |
            echo "Triggered by: ${{ github.actor }}"
            echo "Event type: ${{ github.event_name }}"
            echo "Repository: ${{ github.event.client_payload.source_rep || 'Not specified' }}"
            echo "Reference: ${{ github.event.client_payload.source_ref || 'Not specified' }}"
            echo "Runner: ${{ github.event.client_payload.runner || 'ubuntu-latest (default)' }}"
            echo "Registry type: ${{ github.event.client_payload.registry_type || 'ghcr (default)' }}"
            echo "Dockerfile variant: ${{ github.event.client_payload.dockerfile_variant || 'standard (default)' }}"
            echo "GitHub token source: ${{ github.event.client_payload.github_token && 'payload' || 'secrets' }}"
            echo "ACR credentials source: ${{ github.event.client_payload.acr_username && 'payload' || 'secrets' }}"
            echo "Current runner: ${{ runner.os }}"

        - name: Get more disk space
          uses: jlumbroso/free-disk-space@main
          with:
            tool-cache: false
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true

        - name: Checkout source repository
          uses: actions/checkout@v4
          with:
            repository: ${{ env.SOURCE_REP }}
            token: ${{ github.event.client_payload.github_token }}
            ref: ${{ env.SOURCE_REF }}
            clean: false

        - name: Build local
          uses: ./
          with:
            github_token: ${{ github.event.client_payload.github_token }}
            acr_username: ${{ github.event.client_payload.acr_username }}
            acr_password: ${{ github.event.client_payload.acr_password }}
            acr_serverid: ${{ github.event.client_payload.acr_serverid }}
            registry_type: ${{ github.event.client_payload.registry_type || 'ghcr' }}
            dockerfile_variant: ${{ github.event.client_payload.dockerfile_variant || 'standard' }}
